db:
    mode:  # mysql pgsql sqlite ""
    db_name: fast_db
    host: 127.0.0.1
    port: 3306
    user: root
    password: cy200083
redis:
    addr: ""
    password: ""
    db: 1
system:
    mode: release
    ip: 0.0.0.0
    port: 8080
jwt:
    expiresAt: 8
    issuer: cy
    key: jkliop
upload:
    size: 2  # 上传大小限制MB
    dir: images
site:
    login:
    captcha: true