db:
    mode: mysql # mysql pgsql sqlite ""
    db_name: fast_db
    host: 127.0.0.1
    port: 3306
    user: root
    password: cy200083
redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 1
system:
    mode: release
    ip: 127.0.0.1
    port: 8080